### ISSUE TITLE
Add End to End ClimateMachine.jl example 

### ISSUE THREAD

**Issue by jakebolewski** [CliMA/CalibrateEmulateSample.jl#100]

**Comment by jakebolewski** [comment]
Dependent on `experiments/Atmos/LES/stable_bl_les.jl`

**Comment by odunbar** [comment]
The `EnsembleKalmanProcesses.jl` version of this example has been merged in!

https://github.com/CliMA/EnsembleKalmanProcesses.jl/pull/7
