### ISSUE TITLE
Log posterior calculation

### ISSUE THREAD

**Issue by mhowlan3** [CliMA/CalibrateEmulateSample.jl#105]
There is a potential for numerical issues in the function `log_likelihood` in `MarkovChainMonteCarlo.jl`. If the covariance matrix is ill-conditioned, `det(gvar)` may return Inf.

Currently, `log_gpfidelity = -FT(0.5) * log(det(Diagonal(gvar)))`. This line first computes the full determinant of `gvar` and then takes the log. 

It may be better to take `log_det_gamma = sum(log.(eigvals(gvar)))` if gvar is a full matrix or `log_det_gamma = sum(log.(gvar))` if gvar is a vector of diagonal elements in the SVD transformed space.

**Comment by odunbar** [comment]
Sounds good, Could you implement the `sum(log(gvar))` version immediately?

For the other version, we don't yet have the infrastructure to deal with additional noise inflation for example, which would lead to the nondiagonal matrices here.

**Comment by odunbar** [comment]
Closed in #130
