### ISSUE TITLE
Any tagged releases like v0.1.0 planned?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/CalibrateEmulateSample.jl#110]
Would be helpful to be able to depend on a specific tag/release without having to worry about whether the main branch has changed.

**Comment by jakebolewski** [comment]
I think we first need to tag and register EKP to make managing the dependencies easier

**Comment by odunbar** [comment]
I'd like to think that once we have some starting docs for each this would be a natural time. Perhaps early next week is not unreasonable for this aspiration.

**Comment by glwagner** [comment]
Any update? Note that tagging a release doesn't really make a package more "visible", it's just a slight convenience for users.

**Comment by ilopezgp** [comment]
@glwagner @ali-ramadhan Sorry for not addressing this issue earlier, the first release is here!
