### ISSUE TITLE
LaTeX equation in documentation homepage isn't properly rendered 

### ISSUE THREAD

**Issue by pitmonticone** [CliMA/CalibrateEmulateSample.jl#116]
The LaTeX equation environment in the documentation [homepage](https://clima.github.io/CalibrateEmulateSample.jl/dev/)

```math
\begin{equation}
y = G(u) + \eta
\end{equation},
```

doesn't seem to be properly displayed. 

<img width="383" alt="Screenshot 2021-04-02 at 16 40 36" src="https://user-images.githubusercontent.com/38562595/113425461-2ea65500-93d2-11eb-8644-04c3be1ec1f5.png">

Maybe 

$$
\begin{equation}
y = G(u) + \eta
\end{equation},
$$

can solve the problem. 

Thank you very much for the development of this package.

**Comment by odunbar** [comment]
Thanks very much for your comment. The docs are currently just in a stub form, we are looking to overhaul all of them in the next few weeks! (in tandem with the associated docs for package `EnsembleKalmanProcesses.jl`)

**Comment by tsj5** [comment]
Verified that this is fixed by PR #123 when the docs are built under julia 1.6. That PR doesn't change index.md, which is using (currently) valid syntax for the display equation, so presumably the fix is due to the updated version of Documenter.jl used in that PR.
