### ISSUE TITLE
New Documentation pages request

### ISSUE THREAD

**Issue by odunbar** [CliMA/CalibrateEmulateSample.jl#136]
Updates:
- [x] Clima Logo and Authorship notice - Ollie
- [x] index page modules out-of-date - Ollie

New pages:
- [x] Contributors page - Ollie
- [x] Links to the EKP documentation regarding Priors/Parameter distributions - Ignacio
- [x] Calibration is just EKP (say how it is called, and then link to EKP) - Ignacio
- [x] Data processing (normalization, standardization, SVD, truncation) - Melanie/Mike
- [x] Gaussian process emulator option - Laura/Melanie/Ollie
- [x] general emulator page (how to add new emulators) - Ollie
- [x] Sample stage (RWM MCMC, pCN MCMC) - Tom

**Comment by lm2612** [comment]
I'm happy to get started on the Gaussian process emulator docs
