### ISSUE TITLE
Random Feature development

### ISSUE THREAD

**Issue by odunbar** [CliMA/CalibrateEmulateSample.jl#164]
## Purpose
To create a random feature implementation in Julia as a  `MachineLearningTool`
- [x] Wrapper for Distributions.jl (Wish to sample Univariate distributions, as well as Multivariate Gaussians/Student-t)
- [x] Ability to easily get/set the parameters from such distributions (e.g. mean/std for example), and resample such distributions
- [x] Build Random Fourier Features (i.e. cosine based)
- [x] Build Random Neuron Features (i.e. based on selecting 1D activation functions)
- [x] Fit a 'Random Feature kernel' to data, by solving the relevant LS optimization problem efficiently.
- [x] (Future) Train the hyperparameters of the distributions or regularization (e.g with a derivative free ensemble method)

**Comment by odunbar** [comment]
Hi @nickhnelsen I have tasked @tsj5 with getting a nice modular RF package together for use in CES. 

We will translate from a python repo, but I don't know if you have any julia code written as an entry point already for RF here

**Comment by nickhnelsen** [comment]
Hi Ollie and Tom, I think our Python repo (private on Ollie's account) is the best entry point because my old Julia code was for vector-valued RFs.
I would also suggest adding to the above ToDo's the ability to sample Multivariate Student's t distribution (not just Multivariate Gaussian). In fact, a student's t sample only requires a single Multivariate Gaussian sample plus a uni-variate Chi Square sample: https://en.wikipedia.org/wiki/Multivariate_t-distribution

**Comment by odunbar** [comment]
Hi @nickhnelsen , thanks! Yeah I've already added Tom to the python repo as an entry. I wasn't sure if with all the DARPA grant work there was any existing Julia code worth building on.

**Comment by odunbar** [comment]
## Update
[`RandomFeatures.jl`](https://github.com/CliMA/RandomFeatures.jl) can now perform all of the checklist (why i have ticked them off) 

I'll begin a new branch `orad/RF` to see if we can come up with a good interface for RF in CES using the (currently unregistered version of the package)

**Comment by odunbar** [comment]
Updated todo's - after the PR #194 is merged :
- [ ] interface for passing in hparam algorithm options
- [ ] interface for defining user-priors 
- [ ] SVD truncation for vector RF 
- [ ] Sample stage for GCM application
- [ ] Documentation (beyond API)
