### ISSUE TITLE
Add Windows 32-bit build back in

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/CalibrateEmulateSample.jl#25]
We had to remove Windows 32-bit build in #22 because, while it seemed to be working up to some point, it was timing out and [cannot be increased for non-private builds](https://www.appveyor.com/docs/build-configuration/#build-timeout).

Potential solutions for fixing this seem to be trimming dependencies (especially PyCall/Conda), since only 5-10 minutes are actually needed for testing.

**Comment by dburov190** [comment]
I'm not sure we need to care about win32 to be honest... It's very obsolete now, besides, it's Windows :D

**Comment by charleskawczynski** [comment]
I suspect that it's actually working fine, it's just that we don't know because it's timing out ¯\_(ツ)_/¯.
