### ISSUE TITLE
Sinusoid example not fully reproducible

### ISSUE THREAD

**Issue by matt-graham** [CliMA/CalibrateEmulateSample.jl#283]
Raising as part of JOSS review openjournals/joss-reviews/issues/6372

The sinusoid example in the documentation https://clima.github.io/CalibrateEmulateSample.jl/dev/examples/sinusoid_example/ (and partially included in the JOSS paper), is not fully reproducible. I think this is at least in part due to the use of unseeded random number generators when sampling the observation noise for the simulated observations in
https://github.com/CliMA/CalibrateEmulateSample.jl/blob/6fcab82a690d71ef7c6b3810901da80ba1cfcb43/docs/src/examples/sinusoid_example.md?plain=1#L97-L98
and when simulating the Markov chain in
https://github.com/CliMA/CalibrateEmulateSample.jl/blob/6fcab82a690d71ef7c6b3810901da80ba1cfcb43/docs/src/examples/sinusoid_example.md?plain=1#L359-L365
so that we get different simulated observations from the values mentioned in the tutorial and different Markov chain samples.

There are also a few other small issues which mean the tutorial isn't runnable as is / a complete self-contained example

- [x] Missing imports - for example `Statistics` for the use of `mean` and `Distributions` for the use of `MvNormal`.
- [x] `emulator` variable passed to `MCMCWrapper` not defined (presumably one of `emulator_gp` or `emulator_random_features` should be aliased to this?)
- [x] `init_sample` variable passed as `init_params` argument to `MCMCWrapper` is not defined
- [x] In the random features example there are lots of undefined variables - `nugget`, `n_features`, `input_dim`, `output_dim` (presumably the last two might map to `dim_params` and `dim_output`)

**Comment by odunbar** [comment]
Hi @matt-graham, thanks for raising these issues! 

I'd like to ask was if it clear that the example on our docs page is simply documenting code within [`examples/Sinusoid`](https://github.com/CliMA/CalibrateEmulateSample.jl/tree/main/examples/Sinusoid) on the github? I find that our example code here can be run completely in a self-contained manner, and reproduces all plots etc. 

For example
- `init_sample` is defined [here](https://github.com/CliMA/CalibrateEmulateSample.jl/blob/6fcab82a690d71ef7c6b3810901da80ba1cfcb43/examples/Sinusoid/sample.jl#L50)
- `emulator` is loaded [here](https://github.com/CliMA/CalibrateEmulateSample.jl/blob/6fcab82a690d71ef7c6b3810901da80ba1cfcb43/examples/Sinusoid/sample.jl#L37-L38)
- likewise the random features items are all defined [here and afterwards](https://github.com/CliMA/CalibrateEmulateSample.jl/blob/6fcab82a690d71ef7c6b3810901da80ba1cfcb43/examples/Sinusoid/emulate.jl#L89)

We do want the docs to be good teaching points, and be instructive, but I would say the walkthrough, though featuring snippets, is **not intended to be used to reproduce the example**, whereas the code in the examples directory is intended to reproduce everything (inc. plots etc). 

In light of this I think perhaps we should also add the item 
- [ ] Add a clear link from "documentation of example" -> "full code of example" at the top of example documentation page.

What do you think?

**Comment by nluetts** [comment]
Hi :wave:

I am replying to this also in the context of the JOSS review https://github.com/openjournals/joss-reviews/issues/6372

When I looked at your Sinusoid example in the docs, it was in fact not immediately clear to me that it was intended to describe the Sinusoid example in your `examples` folder, because I was looking at the docs first and the repository only a bit later, and there seems to be no mention of the `examples` folder in the respective section in the docs.
So I think a link in the docs plus an explicit statement about the `examples` folder would be very helpful indeed.

**Comment by matt-graham** [comment]
Apologies for the delay replying - here. I agree with @nluetts that having a link to the full code in the documentation would be useful - I also missed the `examples` folder initially.

**Comment by odunbar** [comment]
@nluetts @matt-graham 

The latest docs [here](https://clima.github.io/CalibrateEmulateSample.jl/dev/examples/sinusoid_example/)

I believe we have cleared up some reproducibility in the example file (PR287) and also a link at the top from the docs page to the examples (PR290) let us know if you want more done here.

**Comment by nluetts** [comment]
The info box in the docs is perfect, now this can hardly be overlooked.

**Comment by matt-graham** [comment]
@odunbar thanks - #287 and #290 address all my points so closing this.
