### ISSUE TITLE
Author list on JOSS paper

### ISSUE THREAD

**Issue by matt-graham** [CliMA/CalibrateEmulateSample.jl#284]
Raising as part of JOSS review openjournals/joss-reviews/issues/6372

One of the points on the reviewed checklist is 

> Does the full list of paper authors seem appropriate and complete?

and the [JOSS ethics guidelines ](https://joss.theoj.org/about#ethics) state that

> Author lists must be correct and complete. All listed authors must have made a contribution to the work, and all significant contributors should be included in the author list.

As there are a few GitHub users who appear from the [GitHub contributors data](https://github.com/CliMA/CalibrateEmulateSample.jl/graphs/contributors) to have made relatively significant contributions to the software who do not appear to be included as authors (namely `dburov190`, `charleskawczynski` and `tsj5` though apologies if I am mismatching names to GitHub usernames) compared to other contributors who have been included as authors, can I check if there has been a discussion with those contributors about authorship and/or if there is some reason for not including them on the author list?

**Comment by odunbar** [comment]
Thanks for the comment. I would validate our author-list choices by saying that the selection contains developers for the CES package, who provided either offline-insights, code developments, or both, and wish to be associated and assume levels of stewardship of the codebase. Regarding your choices

- tsj5 has left the project a couple of years ago and although I would have liked them to be an author, they did not respond to email requests from me to be one. As authorship comes with some responsibility over the code.
- dburov helped with the original setup in the code but wished to dissociate themselves from this project several years ago for a different field of research
- charleskawczynski/sjbyrne/jakebolewski are/were CliMA software developers and certainly provided some contribution to initiating the codebase, initial commits, and maintenance e.g. putting GH workflows/formatting etc. in line with CliMA package ecosystem. They appear as significant contributors, and though their contributions are valuable, I would say they are not "associated" with this codebase, any more than the other packages they maintain.

**Comment by matt-graham** [comment]
Hi @odunbar - thanks for the clarifications. That all seem reasonable so closing this.
