### ISSUE TITLE
Problems installing the package

### ISSUE THREAD

**Issue by plcrodrigues** [CliMA/CalibrateEmulateSample.jl#311]
Hi, everyone. After reading the "Calibrate, Emulate, Sample" paper by Cleary et al. I wanted to play a bit with the algorithms and get a better grasp of the full methodology. I was, therefore, vey happy to see that the paper came with a well structured documentation. Kudos for that! Unfortunately, I was unable to install the package on a newly created environment on my MacBook Air with ARM architecture.

The error that I get after doing
```
julia --project
> ]
> add Conda
> add CalibrateEmulateSample
```

is the following

```
PkgPrecompileError: The following 1 direct dependency failed to precompile:

CalibrateEmulateSample [95e48a1f-0bec-4818-9538-3db4340308e3]

Failed to precompile CalibrateEmulateSample [95e48a1f-0bec-4818-9538-3db4340308e3] to "/Users/plcrodrigues/.julia/compiled/v1.10/CalibrateEmulateSample/jl_Hmh8kk".
WARNING: could not import EnsembleKalmanProcesses.Observations into CalibrateEmulateSample
ERROR: LoadError: UndefVarError: `Observations` not defined
Stacktrace:
 [1] include(mod::Module, _path::String)
   @ Base ./Base.jl:495
 [2] include(x::String)
   @ CalibrateEmulateSample ~/.julia/packages/CalibrateEmulateSample/mK8b2/src/CalibrateEmulateSample.jl:8
 [3] top-level scope
   @ ~/.julia/packages/CalibrateEmulateSample/mK8b2/src/CalibrateEmulateSample.jl:19
 [4] include
   @ ./Base.jl:495 [inlined]
 [5] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2222
 [6] top-level scope
   @ stdin:3
in expression starting at /Users/plcrodrigues/.julia/packages/CalibrateEmulateSample/mK8b2/src/Utilities.jl:1
in expression starting at /Users/plcrodrigues/.julia/packages/CalibrateEmulateSample/mK8b2/src/CalibrateEmulateSample.jl:1
in expression starting at stdin:
```

Am I missing something? (disclaimer: I have near to zero experience with Julia language...)

Thanks for your attention!

**Comment by plcrodrigues** [comment]
Ah, I guess it must be connected to this : https://github.com/CliMA/EnsembleKalmanProcesses.jl/commit/dab5affdb6e4d337ff03fbe571c6caf7d409e2ac 

I installed version 1.1.5 of `EnsembleKalmanProcesses` and it worked fine.

**Comment by odunbar** [comment]
Apologies! Just working on this one - Yeah we overhauled the Observations. I thought it was ok to release it as 1.1.X but should have done 1.2.1

**Comment by odunbar** [comment]
please fix to 1.1.5 for now and it should be resolved ASAP thank you for reporting this

**Comment by plcrodrigues** [comment]
No problem, it forced me to try to understand a bit more of Julia and its inner workings :)

**Comment by odunbar** [comment]
OK the fix is in - 

Currently this is just on `main`, so 
- if you are installing CES locally you can use `git pull` on main to get the changes.
- if you are using the package manager to add CES, `add CalibrateEmulateSample#main` instead of just `add CalibrateEmulateSample` or just `dev` your local version

Hopefully in the next few days I'll release a new version so just the `add` works. (I am still wanting to merge one other PR (#292) before releasing a new version)

**Comment by odunbar** [comment]
Please re-open the issue or create more issues if you have other problems! Thanks for helping improve the code :)
