### ISSUE TITLE
A series of Examples

### ISSUE THREAD

**Issue by odunbar** [CliMA/CalibrateEmulateSample.jl#59]
We propose an example series to demonstrate the CES in various forms of increasing complexity.

- [x] Simple linear model

- [x] Simple nonlinear model

- [x] Linear model with parameter transforms to enforce constraints

- [ ] ... (Please extend as required) 

Coauthored by @bielim @ilopezgp

**Comment by ali-ramadhan** [comment]
I found @sandreza's minimal example very helpful for finding optimal parameters for a linear model with 2 parameters.

I've put it in a gist for easy reference: https://gist.github.com/ali-ramadhan/1edceaa78e550ca220e591d5c6db9aed

![EKI](https://user-images.githubusercontent.com/20099589/102917670-a0761680-4453-11eb-8864-e1e05829f97a.gif)

**Comment by jakebolewski** [comment]
These now exist in CES and EKP, it would be good to open additional issues for more specific examples that would be useful to include.
