### ISSUE TITLE
Insanely long precompile times.

### ISSUE THREAD

**Issue by odunbar** [CliMA/CalibrateEmulateSample.jl#65]
My precompile time is around 10 minutes or more for the package on my laptop (which is still a reasonably good machine). The CES julia code i've used before has a 30 second precompile time...

 I can limit this with `Revise.jl` but it's quite unusable otherwise.

**Comment by jakebolewski** [comment]
When I was updating the CI this took about 17 minutes for me.

I think the only short term practical solution here is to break apart the package to cut down on the number of third party dependencies / and or have a custom sys-image for the dependencies similar to: https://github.com/CliMA/ClimateMachine.jl/tree/master/.dev/systemimage

**Comment by odunbar** [comment]
Yes I think we can strip it out of those, But it's surprising - I have a similar code (which this was based on) and that seems to take on the order of 30seconds to precompile. I'll maybe have a look for differences.

**Comment by jakebolewski** [comment]
Given the way (current) pre-compilation works, you can get into scenarios where there is excessive method invalidation given the mix of packages imported and the methods they extend (one package invalidates a pre-compiled method in another which has cascading consequences).

**Comment by odunbar** [comment]
Is there a way of automatically flushing out deprecated packages from the `project.tml` / `manifest.toml` ?

**Comment by jakebolewski** [comment]
unfortunately no

**Comment by odunbar** [comment]
haha well I guess we will find a way then ;)

**Comment by odunbar** [comment]
Actually, is there a way of isolating certain packages with certain examples then? 

Basically I think the structure is that we have some core packages required by the `src` files (e.g. `LinearAlgebra` ).

But then we also have some `example` files, and for each example we may have 3-4 different packages loaded that are only to run the example (e,g `DifferentialEquations`). These are only to be called when the example is run, but the precompilation will compile everything at once. I'm wondering if we can create these examples as `modules`  which are only compiled when the example is run?

**Comment by glwagner** [comment]
@odunbar you may be able to use test dependencies for the examples.

We use something similar in `Oceananigans.jl`. The examples use `Plots`. Thus to run examples during tests, we permit the tests to depend on `Plots`, even though `Oceananigans` does not depend on `Plots`:

https://github.com/CliMA/Oceananigans.jl/blob/master/Project.toml

Some more info here:

https://discourse.julialang.org/t/how-to-add-a-package-as-a-test-dependency-from-the-repl/14313

**Comment by odunbar** [comment]
Thank Greg! I've had a look. 

For us the examples are to help users see the functionality etc, but a large chunk of the dependencies come from them. the CI tests are much less involved with no additional package dependencies i believe.

So maybe we are in the latter. Your suggestion therefore would be to remove all the examples from this project except for the CI tests. Then create a project for examples (or even _per_ example) which use this package?

**Comment by glwagner** [comment]
Are the examples part of the *package*? You can keep them in the repository without adding their dependencies to `Project.toml`, so long as they are not part of the package (they are not loaded by `src/CalibrateEmulateSample.jl`. 

This is fine I think --- it's best to think of the examples as scripts that demonstrate the functionality of the package (eg, the scripts have `using CalibrateEmulateSample` at the top, and demonstrate how to invoke the package functionality through its API).

If you have many packages that are used by the examples which are not in `Project.toml`, you might considering using a separate environment for examples (another `Project.toml` located in `/examples`).

**Comment by odunbar** [comment]
Yeah it does seem weird to have them part of the package as a whole ;) I mean, if people are going to use the `CalibrateEmulateSample.jl` they are not going to want a bunch of packages that are required for the different examples.

I think this is the best solution, our examples are already written in this form o f a script with `using CalibrateEmulateSample.XYZ` in them. We will remove them from the CES `Project.toml` , and perhaps give the examples their own environment.

RE the [extras]/[targets] Yeah i agree, if it was part of the testing then it would make sense to have these as a 'one-off' load up for this purpose. But yeah

**Comment by bielim** [comment]
Thanks, Greg! We'll try this and report back on whether it reduced the precompile times - I mean, it's worth doing it for "code hygiene" alone, but shorter precompile times would be a nice side effect :-)

**Comment by jakebolewski** [comment]
Another trick is to run with code coverage to see dead code / packages, but I don't know if nowadays that is toplevel package only.

**Comment by glwagner** [comment]
`DifferentialEquations.jl` has notoriously long precompile times. That might be the main culprit?

**Comment by bielim** [comment]
Thanks again for the suggestions! PR #67 substantially reduced the precompile times (by factor 3 and more, depending on the local setup), and so I am closing this now -- following @glwagner's advice, we created a separate environment (i.e., a separate `Project.toml` and `Manifest.toml` file) for each example, such that the main environment now only includes the packages needed for the core Calibrate-Emulate-Sample functionality.
