### ISSUE TITLE
Add Scikit-learn install into a build script for the Project

### ISSUE THREAD

**Issue by odunbar** [CliMA/CalibrateEmulateSample.jl#68]
It seems like the way to get a running version of the project is 
1) Clone the repo
2) Add Conda to the Project
3) Install scikit-learn through Conda (If not already on the system?)
4) Remove Conda

It would be nice to have a build script which constructs this on  `Pkg.build(CalibrateEmulateSample.jl)`

It is likely Conda is required in which case we just want:
1) clone repo
2) install scikit-learn through Conda

**Comment by jakebolewski** [comment]
Ex: pyplot install steps https://github.com/JuliaPy/PyPlot.jl#automated-matplotlib-installation

**Comment by jakebolewski** [comment]
closed by #78
