### ISSUE TITLE
Observations constructor modified given observation covariance

### ISSUE THREAD

**Issue by ilopezgp** [CliMA/CalibrateEmulateSample.jl#71]
The following `Obs` constructor in `Observations.jl`,

```
function Obs(samples::Array{FT, 2},
             obs_noise_cov::Union{Array{FT, 2}, Nothing},
             data_names::Union{Vector{String}, String})where {FT<:AbstractFloat}
```

modifies the given ` obs_noise_cov` when only one sample is given. This behavior precludes the use of this function in the case where we know a priori the observational noise covariance and we have no need to pass a full list of samples to the constructor, just the mean.

**Comment by odunbar** [comment]
Exported out and dealt with in `EnsembleKalmanProcesses.jl`
