### ISSUE TITLE
Use `EnsembleKalmanProcess` rather than `EKObj`?

### ISSUE THREAD

**Issue by glwagner** [CliMA/CalibrateEmulateSample.jl#82]
https://github.com/CliMA/CalibrateEmulateSample.jl/blob/b210ee85f4a4fe9be4223cd8e80f29f6ce7faaeb/src/EKP.jl#L46

`EnsembleKalmanProcess` may be more literal than `EKObj`. Also, using a verbose form for the name will make scripts more readable, especially for non-experts (and a lot of non-statistologists physicsts may read these scripts, considering their application).

cc @odunbar

**Comment by glwagner** [comment]
Likewise, the module `EKP.jl` could be called `EnsembleKalmanProcesses.jl`.

**Comment by ali-ramadhan** [comment]
I second this suggestion. Since it's a breaking change, it would probably be good to do this before tagging a v0.1.0.

**Comment by odunbar** [comment]
Because you asked so nicely, I'm working on a branch to deal with these. `orad/verbose-names` 

I will include filenames and the objects within.
`EKP.jl` -> `EnsembleKalmanProcesses.jl`
`GPEmulator.jl` -> `GaussianProcessEmulator.jl`
`MCMC.jl` -> `MarkovChainMonteCarlo.jl`
